apiVersion: apps/v1
kind: Deployment
metadata:
  name: bills-deployment
spec:
  selector:
    matchLabels:
      app: bills
  replicas: 1
  template:
    metadata:
      labels:
        app: bills
    spec:
      containers:
      - image: gsas/rso-bills:latest
        name: bills
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: azure      
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
          name: server
          protocol: TCP

          
---
          
apiVersion: v1
kind: Service
metadata:
  name: bills
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: bills