apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyers-deployment
spec:
  selector:
    matchLabels:
      app: buyers
  replicas: 1
  template:
    metadata:
      labels:
        app: buyers
    spec:
      containers:
      - image: gsas/rso-buyers:latest
        name: buyers
        env:
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP

          
---
          
apiVersion: v1
kind: Service
metadata:
  name: buyers
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: buyers