apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverers-deployment
spec:
  selector:
    matchLabels:
      app: deliverers
  replicas: 1
  template:
    metadata:
      labels:
        app: deliverers
    spec:
      containers:
      - image: gsas/rso-deliverers:latest
        name: deliverers
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: azure      
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
          name: server
          protocol: TCP

          
---
          
apiVersion: v1
kind: Service
metadata:
  name: deliverers
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: deliverers