apiVersion: apps/v1
kind: Deployment
metadata:
  name: queues-deployment
spec:
  selector:
    matchLabels:
      app: queues
  replicas: 1
  template:
    metadata:
      labels:
        app: queues
    spec:
      containers:
      - image: gsas/rso-queues:latest
        name: queues
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: azure      
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
          name: server
          protocol: TCP

          
---
          
apiVersion: v1
kind: Service
metadata:
  name: queues
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: queues