apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurants-deployment
spec:
  selector:
    matchLabels:
      app: restaurants
  replicas: 1
  template:
    metadata:
      labels:
        app: restaurants
    spec:
      containers:
      - image: gsas/rso-restaurants:latest
        name: restaurants
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: azure      
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: server
          protocol: TCP

          
---
          
apiVersion: v1
kind: Service
metadata:
  name: restaurants
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: restaurants